// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSDSobVTcmt3NVR3uHAaVpOoLu4vIHFEc',
    appId: '1:678592226861:web:4f7fa31bd691a871ed3aa4',
    messagingSenderId: '678592226861',
    projectId: 'multinotif-30689',
    authDomain: 'multinotif-30689.firebaseapp.com',
    storageBucket: 'multinotif-30689.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCabVyIvKuzyDTjoKQZo_FG_Meltkl0O6M',
    appId: '1:678592226861:android:b2d7131ccd7baf41ed3aa4',
    messagingSenderId: '678592226861',
    projectId: 'multinotif-30689',
    storageBucket: 'multinotif-30689.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXv0cS0wY1vi5SbytwLw0p2c8-8OYm9r8',
    appId: '1:678592226861:ios:a82accfbc92e1dc0ed3aa4',
    messagingSenderId: '678592226861',
    projectId: 'multinotif-30689',
    storageBucket: 'multinotif-30689.firebasestorage.app',
    iosBundleId: 'com.example.mposv2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXv0cS0wY1vi5SbytwLw0p2c8-8OYm9r8',
    appId: '1:678592226861:ios:a82accfbc92e1dc0ed3aa4',
    messagingSenderId: '678592226861',
    projectId: 'multinotif-30689',
    storageBucket: 'multinotif-30689.firebasestorage.app',
    iosBundleId: 'com.example.mposv2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSDSobVTcmt3NVR3uHAaVpOoLu4vIHFEc',
    appId: '1:678592226861:web:c20b2cafc77f373fed3aa4',
    messagingSenderId: '678592226861',
    projectId: 'multinotif-30689',
    authDomain: 'multinotif-30689.firebaseapp.com',
    storageBucket: 'multinotif-30689.firebasestorage.app',
  );
}
